### ISSUE TITLE
NodesFile (--nf) is not picked by latest docker image and errors out

### ISSUE THREAD

**Issue by kusbr** [Azure-Samples/iot-edge-opc-plc#157]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Run the latest docker image with --nf or-nodesfile parameter and pass the sample (provided in this [article](https://docs.microsoft.com/en-us/samples/azure-samples/iot-edge-opc-plc/azure-iot-sample-opc-ua-server/)). The nodes are not picked up and an error message is shown in the container logs. This was working fine with earlier docker images

docker run --rm -it --name opcplc -v /home/dev/samplenf.json:/app/data/opc-ua-node-files.json  -p 50000:50000 -p 8080:8080 mcr.microsoft.com/iotedge/opc-plc:latest --pn=50000 --autoaccept
 --sph --sn=5 --sr=10 --st=uint --fn=5 --fr=1 --ft=uint --ctb --scn --lid --lsn --ref --gn=5 --nf=/app/data/opc-ua-node-files.json

samplenf.json file content:
```
{
  "Folder": "MyTelemetry",
  "NodeList": [
    {
      "NodeId": 1023,
      "Name": "ActualSpeed",
      "Description": "Rotational speed"
    },
    {
      "NodeId": "aRMS"
    },
    {
      "NodeId": "1025",
      "Name": "DKW",
      "DataType": "Float",
      "ValueRank": -1,
      "AccessLevel": "CurrentReadOrWrite",
      "Description": "Diagnostic characteristic value"
    }
  ]
}
```

### Any log messages given by the failure
> 
```
[04:29:17 ERR] Error creating address space.
System.ArgumentException: Identifier type not supported. (Parameter 'value')
   at Opc.Ua.NodeId..ctor(Object value, UInt16 namespaceIndex)
   at CallSite.Target(Closure , CallSite , Type , Object , UInt16 )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at OpcPlc.PlcNodeManager.CreateBaseVariable(BaseDataVariableState baseDataVariableState, NodeState parent, Object path, String name, NodeId dataType, Int32 valueRank, Byte accessLevel, String description, NamespaceType namespaceType, Object defaultValue) in D:\a\1\s\src\PlcNodeManager.cs:line 190
   at CallSite.Target(Closure , CallSite , PlcNodeManager , BaseDataVariableState , NodeState , Object , String , NodeId , Int32 , Byte , String , NamespaceType , Object )
   at OpcPlc.PlcNodeManager.CreateBaseVariable(NodeState parent, Object path, String name, NodeId dataType, Int32 valueRank, Byte accessLevel, String description, NamespaceType namespaceType, Object defaultValue) in D:\a\1\s\src\PlcNodeManager.cs:line 145
   at CallSite.Target(Closure , CallSite , PlcNodeManager , NodeState , Object , String , NodeId , Int32 , Byte , String , NamespaceType , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid10[T0,T1,T2,T3,T4,T5,T6,T7,T8,T9](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7, T8 arg8, T9 arg9)
   at OpcPlc.PluginNodes.UserDefinedPluginNodes.CreateBaseVariable(NodeState parent, ConfigNode node) in D:\a\1\s\src\PluginNodes\UserDefinedPluginNodes.cs:line 131
   at OpcPlc.PluginNodes.UserDefinedPluginNodes.AddNodes(FolderState folder) in D:\a\1\s\src\PluginNodes\UserDefinedPluginNodes.cs:line 93
   at OpcPlc.PluginNodes.UserDefinedPluginNodes.AddToAddressSpace(FolderState telemetryFolder, FolderState methodsFolder, PlcNodeManager plcNodeManager) in D:\a\1\s\src\PluginNodes\UserDefinedPluginNodes.cs:line 35
   at OpcPlc.PlcNodeManager.CreateAddressSpace(IDictionary`2 externalReferences) in D:\a\1\s\src\PlcNodeManager.cs:line 68
```

### Expected/desired behavior
> The nodesfile should be picked up and new nodes added to the namespace

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Ubuntu 20.04
Ubuntu 22.04

### Versions
>

### Mention any other details that might be useful
This feature was working fine for a long time and need this :)
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luiscantero** [comment]
@kusbr thanks for reporting this. Apparently the SDK is now rejecting the node ID of type number. If you change the JSON to `"NodeId": "1023"` it will work. I will investigate next week.

**Comment by kusbr** [comment]
Thanks :)
