### ISSUE TITLE
Please help me connect opc UA client with prosys opc UA simulation server step by step: Please help

### ISSUE THREAD

**Issue by georgethomas08** [Azure-Samples/iot-edge-opc-plc#49]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Linux (Ubuntu 20.04)
### Versions
>

### Mention any other details that might be useful
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcClient.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcclient/OpcSession.cs:line 175
[18:45:08 INF] Execute 'OpcClient.OpcTestAction' action on node 'i=2258' on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:08 INF] Action (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258') execution with error
[18:45:08 INF] Result (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258'): BadNotConnected 'Error establishing a connection: BadNotConnected'

[18:45:18 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:18 ERR] Session creation to endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' failed 2 time(s). Please verify if server is up and OpcClient configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcClient.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcclient/OpcSession.cs:line 175
[18:45:18 INF] Execute 'OpcClient.OpcTestAction' action on node 'i=2258' on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:18 INF] Action (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258') execution with error
[18:45:18 INF] Result (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258'): BadNotConnected 'Error establishing a connection: BadNotConnected'
[18:45:28 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:28 ERR] Session creation to endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' failed 3 time(s). Please verify if server is up and OpcClient configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcClient.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcclient/OpcSession.cs:line 175
[18:45:28 INF] Execute 'OpcClient.OpcTestAction' action on node 'i=2258' on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:28 INF] Action (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258') execution with error
[18:45:28 INF] Result (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258'): BadNotConnected 'Error establishing a connection: BadNotConnected'
[18:45:38 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:38 ERR] Session creation to endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' failed 4 time(s). Please verify if server is up and OpcClient configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcClient.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcclient/OpcSession.cs:line 175
[18:45:38 INF] Execute 'OpcClient.OpcTestAction' action on node 'i=2258' on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:38 INF] Action (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258') execution with error
[18:45:38 INF] Result (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258'): BadNotConnected 'Error establishing a connection: BadNotConnected'
[18:45:48 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:48 ERR] Session creation to endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' failed 5 time(s). Please verify if server is up and OpcClient configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcClient.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcclient/OpcSession.cs:line 175
[18:45:48 INF] Execute 'OpcClient.OpcTestAction' action on node 'i=2258' on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:48 INF] Action (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258') execution with error
[18:45:48 INF] Result (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258'): BadNotConnected 'Error establishing a connection: BadNotConnected'
[18:45:58 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:58 ERR] Session creation to endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' failed 6 time(s). Please verify if server is up and OpcClient configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcClient.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcclient/OpcSession.cs:line 175
[18:45:58 INF] Execute 'OpcClient.OpcTestAction' action on node 'i=2258' on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:45:58 INF] Action (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258') execution with error
[18:45:58 INF] Result (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258'): BadNotConnected 'Error establishing a connection: BadNotConnected'
[18:46:08 INF] Connect and monitor session and nodes on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:46:08 ERR] Session creation to endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' failed 7 time(s). Please verify if server is up and OpcClient configuration is correct.
Opc.Ua.ServiceResultException: Error establishing a connection: BadNotConnected
   at Opc.Ua.Bindings.ChannelAsyncOperation`1.End(Int32 timeout, Boolean throwOnError)
   at Opc.Ua.Bindings.UaSCUaBinaryClientChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.EndSendRequest(IAsyncResult result)
   at Opc.Ua.Bindings.UaSCUaBinaryTransportChannel.SendRequest(IServiceRequest request)
   at Opc.Ua.DiscoveryClient.GetEndpoints(RequestHeader requestHeader, String endpointUrl, StringCollection localeIds, StringCollection profileUris, EndpointDescriptionCollection& endpoints)
   at Opc.Ua.DiscoveryClient.GetEndpoints(StringCollection profileUris)
   at Opc.Ua.Client.CoreClientUtils.SelectEndpoint(String discoveryUrl, Boolean useSecurity, Int32 operationTimeout)
   at OpcClient.OpcSession.ConnectSessionAsync(CancellationToken ct) in /app/opcclient/OpcSession.cs:line 175
[18:46:08 INF] Execute 'OpcClient.OpcTestAction' action on node 'i=2258' on endpoint 'opc.tcp://ng:53530/OPCUA/SimulationServer' with security.
[18:46:08 INF] Action (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258') execution with error
[18:46:08 INF] Result (ActionId: 000 ActionType: 'OpcTestAction', Endpoint: 'opc.tcp://ng:53530/OPCUA/SimulationServer' Node 'i=2258'): BadNotConnected 'Error establishing a connection: BadNotConnected'
^X^C[18:46:12 INF] 
[18:46:12 INF] 
[18:46:12 INF] OpcClient is shutting down...

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by luiscantero** [comment]
@georgethomas08 this repository is for the OPC-PLC (server). Your trace is for the [OPC client](https://github.com/Azure-Samples/iot-edge-opc-client/).

Anyhow, to troubleshoot your issue, you should try to connect using another client, such as UaExpert. The error seems to be that the server is not running or not in the same network as the client, or a firewall rule is blocking the connection.
